[[link-roll]]
title = "Example Title 1"
text = "Example Text 1"
image = "/path/to/image1.jpg"
url = "https://example.com/page1"

[[link-roll]]
title = "Example Title 2"
text = "Example Text 2"
image = "/path/to/image2.jpg"
url = "https://example.com/page2"

[[link-roll]]
title = "Example Title 3"
text = "Example Text 3"
image = "/path/to/image3.jpg"
url = "https://example.com/page3"
